# Generated by Django 3.1.7 on 2021-04-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('spk', models.IntegerField(primary_key=True, serialize=False)),
                ('zona', models.CharField(choices=[('Barat', 'Barat'), ('Utara', 'Utara'), ('Timur', 'Timur'), ('Selatan', 'Selatan')], max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('alamat', models.CharField(max_length=200, null=True)),
                ('tanggal', models.DateField(null=True)),
                ('gangguan', models.CharField(max_length=200, null=True)),
                ('jenis', models.CharField(choices=[('Persil', 'Persil'), ('Trandist', 'Trandist')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Penanganan', 'Penanganan'), ('Selesai', 'Selesai')], max_length=200, null=True)),
            ],
        ),
    ]
