# Generated by Django 3.1.7 on 2021-04-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
